version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "8000:80"
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=database_name"
      - "DB_USERNAME=database_username"
      - "DB_PASSWORD=database_password"
    depends_on:
      - mysql
    user: root

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=database_username
      - MYSQL_PASSWORD=database_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"